//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinpe_PIN
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRequestBody", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    public partial class BaseRequestBody : object
    {
        
        private Sinpe_PIN.BaseRequest BaseRequestField;
        
        private Sinpe_PIN.IModelosRastroSIF rastroField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinpe_PIN.BaseRequest BaseRequest
        {
            get
            {
                return this.BaseRequestField;
            }
            set
            {
                this.BaseRequestField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinpe_PIN.IModelosRastroSIF rastro
        {
            get
            {
                return this.rastroField;
            }
            set
            {
                this.rastroField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseRequest", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sinpe_PIN.ReqPINSending))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sinpe_PIN.ReqAccountInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sinpe_PIN.ReqPINEntity))]
    public partial class BaseRequest : object
    {
        
        private string ClientIpAddressField;
        
        private string CultureCodeField;
        
        private string HostIdField;
        
        private System.Guid OperationIdField;
        
        private string UserCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ClientIpAddress
        {
            get
            {
                return this.ClientIpAddressField;
            }
            set
            {
                this.ClientIpAddressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CultureCode
        {
            get
            {
                return this.CultureCodeField;
            }
            set
            {
                this.CultureCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HostId
        {
            get
            {
                return this.HostIdField;
            }
            set
            {
                this.HostIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OperationId
        {
            get
            {
                return this.OperationIdField;
            }
            set
            {
                this.OperationIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserCode
        {
            get
            {
                return this.UserCodeField;
            }
            set
            {
                this.UserCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IModelos.RastroSIF", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    public partial class IModelosRastroSIF : object
    {
        
        private string EquipoField;
        
        private string IPField;
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Equipo
        {
            get
            {
                return this.EquipoField;
            }
            set
            {
                this.EquipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP
        {
            get
            {
                return this.IPField;
            }
            set
            {
                this.IPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReqPINSending", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    public partial class ReqPINSending : Sinpe_PIN.BaseRequest
    {
        
        private System.Nullable<int> CoreIntegrationPointField;
        
        private System.Nullable<int> CostCenterField;
        
        private Sinpe_PIN.PINTransfer TransferField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CoreIntegrationPoint
        {
            get
            {
                return this.CoreIntegrationPointField;
            }
            set
            {
                this.CoreIntegrationPointField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CostCenter
        {
            get
            {
                return this.CostCenterField;
            }
            set
            {
                this.CostCenterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinpe_PIN.PINTransfer Transfer
        {
            get
            {
                return this.TransferField;
            }
            set
            {
                this.TransferField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReqAccountInfo", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    public partial class ReqAccountInfo : Sinpe_PIN.BaseRequest
    {
        
        private string AccountNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReqPINEntity", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    public partial class ReqPINEntity : Sinpe_PIN.BaseRequest
    {
        
        private string AccountNumberField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PINTransfer", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    public partial class PINTransfer : object
    {
        
        private decimal AmountField;
        
        private string ChannelRefNumberField;
        
        private string CurrencyCodeField;
        
        private Sinpe_PIN.CustomField[] CustomDataField;
        
        private string DescriptionField;
        
        private Sinpe_PIN.DestinationCustomer DestinationCustomerField;
        
        private Sinpe_PIN.OriginCustomer OriginCustomerField;
        
        private string OriginEntityIBANField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChannelRefNumber
        {
            get
            {
                return this.ChannelRefNumberField;
            }
            set
            {
                this.ChannelRefNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyCode
        {
            get
            {
                return this.CurrencyCodeField;
            }
            set
            {
                this.CurrencyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinpe_PIN.CustomField[] CustomData
        {
            get
            {
                return this.CustomDataField;
            }
            set
            {
                this.CustomDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinpe_PIN.DestinationCustomer DestinationCustomer
        {
            get
            {
                return this.DestinationCustomerField;
            }
            set
            {
                this.DestinationCustomerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinpe_PIN.OriginCustomer OriginCustomer
        {
            get
            {
                return this.OriginCustomerField;
            }
            set
            {
                this.OriginCustomerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OriginEntityIBAN
        {
            get
            {
                return this.OriginEntityIBANField;
            }
            set
            {
                this.OriginEntityIBANField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DestinationCustomer", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sinpe_PIN.OriginCustomer))]
    public partial class DestinationCustomer : object
    {
        
        private string EmailField;
        
        private string IBANField;
        
        private string IdField;
        
        private int IdTypeField;
        
        private string NameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IBAN
        {
            get
            {
                return this.IBANField;
            }
            set
            {
                this.IBANField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdType
        {
            get
            {
                return this.IdTypeField;
            }
            set
            {
                this.IdTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OriginCustomer", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    public partial class OriginCustomer : Sinpe_PIN.DestinationCustomer
    {
        
        private System.Nullable<bool> DebitIBANField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DebitIBAN
        {
            get
            {
                return this.DebitIBANField;
            }
            set
            {
                this.DebitIBANField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomField", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    public partial class CustomField : object
    {
        
        private string NameField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BaseResponse", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sinpe_PIN.ResPINSending))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sinpe_PIN.ResAccountInfo))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sinpe_PIN.ResServiceAvailable))]
    public partial class BaseResponse : object
    {
        
        private Sinpe_PIN.Errores[] ErrorsField;
        
        private bool IsSuccessfulField;
        
        private string OperationIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinpe_PIN.Errores[] Errors
        {
            get
            {
                return this.ErrorsField;
            }
            set
            {
                this.ErrorsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsSuccessful
        {
            get
            {
                return this.IsSuccessfulField;
            }
            set
            {
                this.IsSuccessfulField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperationId
        {
            get
            {
                return this.OperationIdField;
            }
            set
            {
                this.OperationIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResPINSending", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    public partial class ResPINSending : Sinpe_PIN.BaseResponse
    {
        
        private Sinpe_PIN.PINSendingResult PINSendingResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinpe_PIN.PINSendingResult PINSendingResult
        {
            get
            {
                return this.PINSendingResultField;
            }
            set
            {
                this.PINSendingResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResAccountInfo", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    public partial class ResAccountInfo : Sinpe_PIN.BaseResponse
    {
        
        private Sinpe_PIN.Account AccountField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinpe_PIN.Account Account
        {
            get
            {
                return this.AccountField;
            }
            set
            {
                this.AccountField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResServiceAvailable", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    public partial class ResServiceAvailable : Sinpe_PIN.BaseResponse
    {
        
        private bool ServiceAvailableField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ServiceAvailable
        {
            get
            {
                return this.ServiceAvailableField;
            }
            set
            {
                this.ServiceAvailableField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Errores", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    public partial class Errores : object
    {
        
        private int CodeField;
        
        private string MessageField;
        
        private int TypeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Type
        {
            get
            {
                return this.TypeField;
            }
            set
            {
                this.TypeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PINSendingResult", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    public partial class PINSendingResult : object
    {
        
        private string CBTrxNumberField;
        
        private long CGPRefNumberField;
        
        private string ChannelRefNumberField;
        
        private decimal ComissionAmountField;
        
        private Sinpe_PIN.CustomField[] CustomDataField;
        
        private string DebitCurrencyCodeField;
        
        private decimal DebitedAmountField;
        
        private decimal ExchangeRateField;
        
        private int RejectCodeField;
        
        private string RejectDescriptionField;
        
        private string SINPERefNumberField;
        
        private short StateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CBTrxNumber
        {
            get
            {
                return this.CBTrxNumberField;
            }
            set
            {
                this.CBTrxNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CGPRefNumber
        {
            get
            {
                return this.CGPRefNumberField;
            }
            set
            {
                this.CGPRefNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChannelRefNumber
        {
            get
            {
                return this.ChannelRefNumberField;
            }
            set
            {
                this.ChannelRefNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ComissionAmount
        {
            get
            {
                return this.ComissionAmountField;
            }
            set
            {
                this.ComissionAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinpe_PIN.CustomField[] CustomData
        {
            get
            {
                return this.CustomDataField;
            }
            set
            {
                this.CustomDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DebitCurrencyCode
        {
            get
            {
                return this.DebitCurrencyCodeField;
            }
            set
            {
                this.DebitCurrencyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal DebitedAmount
        {
            get
            {
                return this.DebitedAmountField;
            }
            set
            {
                this.DebitedAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal ExchangeRate
        {
            get
            {
                return this.ExchangeRateField;
            }
            set
            {
                this.ExchangeRateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RejectCode
        {
            get
            {
                return this.RejectCodeField;
            }
            set
            {
                this.RejectCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RejectDescription
        {
            get
            {
                return this.RejectDescriptionField;
            }
            set
            {
                this.RejectDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SINPERefNumber
        {
            get
            {
                return this.SINPERefNumberField;
            }
            set
            {
                this.SINPERefNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Account", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    public partial class Account : object
    {
        
        private string AccountNumberField;
        
        private string CountryCodeField;
        
        private string CountryNameField;
        
        private string CurrencyCodeField;
        
        private int CurrencyHstIdField;
        
        private string CurrencyNameField;
        
        private string CurrencySymbolField;
        
        private string EntityCodeField;
        
        private string EntityNameField;
        
        private string HolderField;
        
        private string HolderIdField;
        
        private int HolderIdTypeField;
        
        private string HolderIdTypeNameField;
        
        private string ProductNameField;
        
        private string StateField;
        
        private string StateNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AccountNumber
        {
            get
            {
                return this.AccountNumberField;
            }
            set
            {
                this.AccountNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryCode
        {
            get
            {
                return this.CountryCodeField;
            }
            set
            {
                this.CountryCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CountryName
        {
            get
            {
                return this.CountryNameField;
            }
            set
            {
                this.CountryNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyCode
        {
            get
            {
                return this.CurrencyCodeField;
            }
            set
            {
                this.CurrencyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrencyHstId
        {
            get
            {
                return this.CurrencyHstIdField;
            }
            set
            {
                this.CurrencyHstIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyName
        {
            get
            {
                return this.CurrencyNameField;
            }
            set
            {
                this.CurrencyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencySymbol
        {
            get
            {
                return this.CurrencySymbolField;
            }
            set
            {
                this.CurrencySymbolField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityCode
        {
            get
            {
                return this.EntityCodeField;
            }
            set
            {
                this.EntityCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EntityName
        {
            get
            {
                return this.EntityNameField;
            }
            set
            {
                this.EntityNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Holder
        {
            get
            {
                return this.HolderField;
            }
            set
            {
                this.HolderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HolderId
        {
            get
            {
                return this.HolderIdField;
            }
            set
            {
                this.HolderIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int HolderIdType
        {
            get
            {
                return this.HolderIdTypeField;
            }
            set
            {
                this.HolderIdTypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string HolderIdTypeName
        {
            get
            {
                return this.HolderIdTypeNameField;
            }
            set
            {
                this.HolderIdTypeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName
        {
            get
            {
                return this.ProductNameField;
            }
            set
            {
                this.ProductNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State
        {
            get
            {
                return this.StateField;
            }
            set
            {
                this.StateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateName
        {
            get
            {
                return this.StateNameField;
            }
            set
            {
                this.StateNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReqPINSendingBody", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    public partial class ReqPINSendingBody : object
    {
        
        private Sinpe_PIN.ReqPINSending ReqPINSendingField;
        
        private Sinpe_PIN.IModelosRastroSIF rastroField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinpe_PIN.ReqPINSending ReqPINSending
        {
            get
            {
                return this.ReqPINSendingField;
            }
            set
            {
                this.ReqPINSendingField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinpe_PIN.IModelosRastroSIF rastro
        {
            get
            {
                return this.rastroField;
            }
            set
            {
                this.rastroField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReqAccountInfoBody", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    public partial class ReqAccountInfoBody : object
    {
        
        private Sinpe_PIN.ReqAccountInfo ReqAccountInfoField;
        
        private Sinpe_PIN.IModelosRastroSIF rastroField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinpe_PIN.ReqAccountInfo ReqAccountInfo
        {
            get
            {
                return this.ReqAccountInfoField;
            }
            set
            {
                this.ReqAccountInfoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinpe_PIN.IModelosRastroSIF rastro
        {
            get
            {
                return this.rastroField;
            }
            set
            {
                this.rastroField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReqPINEntityBody", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    public partial class ReqPINEntityBody : object
    {
        
        private Sinpe_PIN.ReqPINEntity ReqPINEntityField;
        
        private Sinpe_PIN.IModelosRastroSIF rastroField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinpe_PIN.ReqPINEntity ReqPINEntity
        {
            get
            {
                return this.ReqPINEntityField;
            }
            set
            {
                this.ReqPINEntityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinpe_PIN.IModelosRastroSIF rastro
        {
            get
            {
                return this.rastroField;
            }
            set
            {
                this.rastroField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ResPINEntity", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    public partial class ResPINEntity : object
    {
        
        private bool PINEntityField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool PINEntity
        {
            get
            {
                return this.PINEntityField;
            }
            set
            {
                this.PINEntityField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Sinpe_PIN.ISINPE_PIN")]
    public interface ISINPE_PIN
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISINPE_PIN/IsServiceAvailable", ReplyAction="http://tempuri.org/ISINPE_PIN/IsServiceAvailableResponse")]
        System.Threading.Tasks.Task<Sinpe_PIN.ResServiceAvailable> IsServiceAvailableAsync(Sinpe_PIN.BaseRequestBody contexto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISINPE_PIN/SendTransfer", ReplyAction="http://tempuri.org/ISINPE_PIN/SendTransferResponse")]
        System.Threading.Tasks.Task<Sinpe_PIN.ResPINSending> SendTransferAsync(Sinpe_PIN.ReqPINSendingBody TransferData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISINPE_PIN/GetAccountInfo", ReplyAction="http://tempuri.org/ISINPE_PIN/GetAccountInfoResponse")]
        System.Threading.Tasks.Task<Sinpe_PIN.ResAccountInfo> GetAccountInfoAsync(Sinpe_PIN.ReqAccountInfoBody AccountData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISINPE_PIN/IsPINEntity", ReplyAction="http://tempuri.org/ISINPE_PIN/IsPINEntityResponse")]
        System.Threading.Tasks.Task<Sinpe_PIN.ResPINEntity> IsPINEntityAsync(Sinpe_PIN.ReqPINEntityBody PINEntity);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ISINPE_PINChannel : Sinpe_PIN.ISINPE_PIN, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class SINPE_PINClient : System.ServiceModel.ClientBase<Sinpe_PIN.ISINPE_PIN>, Sinpe_PIN.ISINPE_PIN
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SINPE_PINClient() : 
                base(SINPE_PINClient.GetDefaultBinding(), SINPE_PINClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISINPE_PIN.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SINPE_PINClient(EndpointConfiguration endpointConfiguration) : 
                base(SINPE_PINClient.GetBindingForEndpoint(endpointConfiguration), SINPE_PINClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SINPE_PINClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SINPE_PINClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SINPE_PINClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SINPE_PINClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SINPE_PINClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<Sinpe_PIN.ResServiceAvailable> IsServiceAvailableAsync(Sinpe_PIN.BaseRequestBody contexto)
        {
            return base.Channel.IsServiceAvailableAsync(contexto);
        }
        
        public System.Threading.Tasks.Task<Sinpe_PIN.ResPINSending> SendTransferAsync(Sinpe_PIN.ReqPINSendingBody TransferData)
        {
            return base.Channel.SendTransferAsync(TransferData);
        }
        
        public System.Threading.Tasks.Task<Sinpe_PIN.ResAccountInfo> GetAccountInfoAsync(Sinpe_PIN.ReqAccountInfoBody AccountData)
        {
            return base.Channel.GetAccountInfoAsync(AccountData);
        }
        
        public System.Threading.Tasks.Task<Sinpe_PIN.ResPINEntity> IsPINEntityAsync(Sinpe_PIN.ReqPINEntityBody PINEntity)
        {
            return base.Channel.IsPINEntityAsync(PINEntity);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISINPE_PIN))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISINPE_PIN))
            {
                return new System.ServiceModel.EndpointAddress("http://172.16.70.55/Servicios/SINPE_PIN.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SINPE_PINClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISINPE_PIN);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SINPE_PINClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISINPE_PIN);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISINPE_PIN,
        }
    }
}
