//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FactElectronica
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FE_Facturacion", Namespace="http://schemas.datacontract.org/2004/07/FacturacionElectronica.ETL.Core")]
    public partial class FE_Facturacion : object
    {
        
        private FactElectronica.FE_JsonLineas[] DetallesField;
        
        private FactElectronica.FE_JsonEncabezado EncabezadoField;
        
        private FactElectronica.FE_ParametrosSistemas ParametrosField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FactElectronica.FE_JsonLineas[] Detalles
        {
            get
            {
                return this.DetallesField;
            }
            set
            {
                this.DetallesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FactElectronica.FE_JsonEncabezado Encabezado
        {
            get
            {
                return this.EncabezadoField;
            }
            set
            {
                this.EncabezadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FactElectronica.FE_ParametrosSistemas Parametros
        {
            get
            {
                return this.ParametrosField;
            }
            set
            {
                this.ParametrosField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FE_JsonEncabezado", Namespace="http://schemas.datacontract.org/2004/07/FacturacionElectronica.ETL.Core.JsonObjec" +
        "t")]
    public partial class FE_JsonEncabezado : object
    {
        
        private byte CantDeciField;
        
        private long CodigoActividadField;
        
        private byte CondicionVentaField;
        
        private System.DateTime FechaFacturaField;
        
        private short[] MedioPagoField;
        
        private short MonedaField;
        
        private FactElectronica.FE_JsonReceptor ReceptorField;
        
        private byte SituacionEnvioField;
        
        private short SucursalField;
        
        private int TerminalField;
        
        private byte TipoDocField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte CantDeci
        {
            get
            {
                return this.CantDeciField;
            }
            set
            {
                this.CantDeciField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long CodigoActividad
        {
            get
            {
                return this.CodigoActividadField;
            }
            set
            {
                this.CodigoActividadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte CondicionVenta
        {
            get
            {
                return this.CondicionVentaField;
            }
            set
            {
                this.CondicionVentaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaFactura
        {
            get
            {
                return this.FechaFacturaField;
            }
            set
            {
                this.FechaFacturaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short[] MedioPago
        {
            get
            {
                return this.MedioPagoField;
            }
            set
            {
                this.MedioPagoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Moneda
        {
            get
            {
                return this.MonedaField;
            }
            set
            {
                this.MonedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FactElectronica.FE_JsonReceptor Receptor
        {
            get
            {
                return this.ReceptorField;
            }
            set
            {
                this.ReceptorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte SituacionEnvio
        {
            get
            {
                return this.SituacionEnvioField;
            }
            set
            {
                this.SituacionEnvioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short Sucursal
        {
            get
            {
                return this.SucursalField;
            }
            set
            {
                this.SucursalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Terminal
        {
            get
            {
                return this.TerminalField;
            }
            set
            {
                this.TerminalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte TipoDoc
        {
            get
            {
                return this.TipoDocField;
            }
            set
            {
                this.TipoDocField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FE_ParametrosSistemas", Namespace="http://schemas.datacontract.org/2004/07/FacturacionElectronica.ETL.Core")]
    public partial class FE_ParametrosSistemas : object
    {
        
        private string NotasField;
        
        private string NumeroDeComprobanteField;
        
        private string Referencia1Field;
        
        private string Referencia2Field;
        
        private string Referencia3Field;
        
        private string SistemaSiglasField;
        
        private string TipoDocumentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Notas
        {
            get
            {
                return this.NotasField;
            }
            set
            {
                this.NotasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroDeComprobante
        {
            get
            {
                return this.NumeroDeComprobanteField;
            }
            set
            {
                this.NumeroDeComprobanteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referencia1
        {
            get
            {
                return this.Referencia1Field;
            }
            set
            {
                this.Referencia1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referencia2
        {
            get
            {
                return this.Referencia2Field;
            }
            set
            {
                this.Referencia2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Referencia3
        {
            get
            {
                return this.Referencia3Field;
            }
            set
            {
                this.Referencia3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SistemaSiglas
        {
            get
            {
                return this.SistemaSiglasField;
            }
            set
            {
                this.SistemaSiglasField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoDocumento
        {
            get
            {
                return this.TipoDocumentoField;
            }
            set
            {
                this.TipoDocumentoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FE_JsonLineas", Namespace="http://schemas.datacontract.org/2004/07/FacturacionElectronica.ETL.Core.JsonObjec" +
        "t")]
    public partial class FE_JsonLineas : object
    {
        
        private double CantidadField;
        
        private string[] CodProdServField;
        
        private long[] CodTipoField;
        
        private string CodigoField;
        
        private string DescripcionField;
        
        private FactElectronica.FE_JsonDescuentos[] DescuentosField;
        
        private FactElectronica.FE_JsonImpuestos[] ImpuestosField;
        
        private double PrecioUnitarioField;
        
        private string UnidadComercialField;
        
        private short UnidadMedidaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Cantidad
        {
            get
            {
                return this.CantidadField;
            }
            set
            {
                this.CantidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] CodProdServ
        {
            get
            {
                return this.CodProdServField;
            }
            set
            {
                this.CodProdServField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] CodTipo
        {
            get
            {
                return this.CodTipoField;
            }
            set
            {
                this.CodTipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Codigo
        {
            get
            {
                return this.CodigoField;
            }
            set
            {
                this.CodigoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FactElectronica.FE_JsonDescuentos[] Descuentos
        {
            get
            {
                return this.DescuentosField;
            }
            set
            {
                this.DescuentosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FactElectronica.FE_JsonImpuestos[] Impuestos
        {
            get
            {
                return this.ImpuestosField;
            }
            set
            {
                this.ImpuestosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PrecioUnitario
        {
            get
            {
                return this.PrecioUnitarioField;
            }
            set
            {
                this.PrecioUnitarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UnidadComercial
        {
            get
            {
                return this.UnidadComercialField;
            }
            set
            {
                this.UnidadComercialField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short UnidadMedida
        {
            get
            {
                return this.UnidadMedidaField;
            }
            set
            {
                this.UnidadMedidaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FE_JsonDescuentos", Namespace="http://schemas.datacontract.org/2004/07/FacturacionElectronica.ETL.Core.JsonObjec" +
        "t")]
    public partial class FE_JsonDescuentos : object
    {
        
        private string DetalleDescuentoField;
        
        private double MontoDescuentoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DetalleDescuento
        {
            get
            {
                return this.DetalleDescuentoField;
            }
            set
            {
                this.DetalleDescuentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MontoDescuento
        {
            get
            {
                return this.MontoDescuentoField;
            }
            set
            {
                this.MontoDescuentoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FE_JsonImpuestos", Namespace="http://schemas.datacontract.org/2004/07/FacturacionElectronica.ETL.Core.JsonObjec" +
        "t")]
    public partial class FE_JsonImpuestos : object
    {
        
        private byte CodigoImpField;
        
        private byte CodigoTarifaField;
        
        private double FactorIVAField;
        
        private double MontoExportacionField;
        
        private double MontoImpField;
        
        private double PorcentajeImpField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte CodigoImp
        {
            get
            {
                return this.CodigoImpField;
            }
            set
            {
                this.CodigoImpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public byte CodigoTarifa
        {
            get
            {
                return this.CodigoTarifaField;
            }
            set
            {
                this.CodigoTarifaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double FactorIVA
        {
            get
            {
                return this.FactorIVAField;
            }
            set
            {
                this.FactorIVAField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MontoExportacion
        {
            get
            {
                return this.MontoExportacionField;
            }
            set
            {
                this.MontoExportacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double MontoImp
        {
            get
            {
                return this.MontoImpField;
            }
            set
            {
                this.MontoImpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double PorcentajeImp
        {
            get
            {
                return this.PorcentajeImpField;
            }
            set
            {
                this.PorcentajeImpField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FE_JsonReceptor", Namespace="http://schemas.datacontract.org/2004/07/FacturacionElectronica.ETL.Core.JsonObjec" +
        "t")]
    public partial class FE_JsonReceptor : object
    {
        
        private string CorreoField;
        
        private string IdentificacionField;
        
        private string NombreField;
        
        private System.Nullable<byte> TipoIdentField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Correo
        {
            get
            {
                return this.CorreoField;
            }
            set
            {
                this.CorreoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificacion
        {
            get
            {
                return this.IdentificacionField;
            }
            set
            {
                this.IdentificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<byte> TipoIdent
        {
            get
            {
                return this.TipoIdentField;
            }
            set
            {
                this.TipoIdentField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FE_JsonReferencia", Namespace="http://schemas.datacontract.org/2004/07/FacturacionElectronica.ETL.Core.JsonObjec" +
        "t")]
    public partial class FE_JsonReferencia : object
    {
        
        private short AccionRefField;
        
        private System.DateTime FechaRefField;
        
        private string NumeroRefField;
        
        private string RazonNotaField;
        
        private short TipoDocRefField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short AccionRef
        {
            get
            {
                return this.AccionRefField;
            }
            set
            {
                this.AccionRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaRef
        {
            get
            {
                return this.FechaRefField;
            }
            set
            {
                this.FechaRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroRef
        {
            get
            {
                return this.NumeroRefField;
            }
            set
            {
                this.NumeroRefField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonNota
        {
            get
            {
                return this.RazonNotaField;
            }
            set
            {
                this.RazonNotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public short TipoDocRef
        {
            get
            {
                return this.TipoDocRefField;
            }
            set
            {
                this.TipoDocRefField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FactElectronica.IServicio")]
    public interface IServicio
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/ProcesarDocumento", ReplyAction="http://tempuri.org/IServicio/ProcesarDocumentoResponse")]
        System.Threading.Tasks.Task<bool> ProcesarDocumentoAsync(FactElectronica.FE_Facturacion Facturacion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/EnviarDocumento", ReplyAction="http://tempuri.org/IServicio/EnviarDocumentoResponse")]
        System.Threading.Tasks.Task<bool> EnviarDocumentoAsync(long IdEncabezado);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServicio/AnularDocumento", ReplyAction="http://tempuri.org/IServicio/AnularDocumentoResponse")]
        System.Threading.Tasks.Task<bool> AnularDocumentoAsync(FactElectronica.FE_JsonReferencia Referencia, double MontoNoExento, double MontoExento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface IServicioChannel : FactElectronica.IServicio, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ServicioClient : System.ServiceModel.ClientBase<FactElectronica.IServicio>, FactElectronica.IServicio
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServicioClient() : 
                base(ServicioClient.GetDefaultBinding(), ServicioClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServicio.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioClient(EndpointConfiguration endpointConfiguration) : 
                base(ServicioClient.GetBindingForEndpoint(endpointConfiguration), ServicioClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServicioClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServicioClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServicioClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> ProcesarDocumentoAsync(FactElectronica.FE_Facturacion Facturacion)
        {
            return base.Channel.ProcesarDocumentoAsync(Facturacion);
        }
        
        public System.Threading.Tasks.Task<bool> EnviarDocumentoAsync(long IdEncabezado)
        {
            return base.Channel.EnviarDocumentoAsync(IdEncabezado);
        }
        
        public System.Threading.Tasks.Task<bool> AnularDocumentoAsync(FactElectronica.FE_JsonReferencia Referencia, double MontoNoExento, double MontoExento)
        {
            return base.Channel.AnularDocumentoAsync(Referencia, MontoNoExento, MontoExento);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicio))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServicio))
            {
                return new System.ServiceModel.EndpointAddress("http://172.16.70.87/Servicio.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServicioClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServicio);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServicioClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServicio);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServicio,
        }
    }
}
