//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinpe_TFT
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IModelos.RastroSIF", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    public partial class IModelosRastroSIF : object
    {
        
        private string EquipoField;
        
        private string IPField;
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Equipo
        {
            get
            {
                return this.EquipoField;
            }
            set
            {
                this.EquipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP
        {
            get
            {
                return this.IPField;
            }
            set
            {
                this.IPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistrarDirectoDebitoCuentaBody", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    public partial class RegistrarDirectoDebitoCuentaBody : object
    {
        
        private Sinpe_TFT.EnvioDirectoDebitoCuentaRequestBody bodyField;
        
        private Sinpe_TFT.IModelosRastroSIF rastroField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinpe_TFT.EnvioDirectoDebitoCuentaRequestBody body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinpe_TFT.IModelosRastroSIF rastro
        {
            get
            {
                return this.rastroField;
            }
            set
            {
                this.rastroField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnvioDirectoDebitoCuentaRequestBody", Namespace="http://www.prosoft.cr/CGPCanalesIBAN/TFT/")]
    public partial class EnvioDirectoDebitoCuentaRequestBody : object
    {
        
        private Sinpe_TFT.Rastro RastroField;
        
        private Sinpe_TFT.Transferencia[] TransaccionesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Sinpe_TFT.Rastro Rastro
        {
            get
            {
                return this.RastroField;
            }
            set
            {
                this.RastroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Sinpe_TFT.Transferencia[] Transacciones
        {
            get
            {
                return this.TransaccionesField;
            }
            set
            {
                this.TransaccionesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rastro", Namespace="http://www.prosoft.cr/CGPCanalesIBAN/TFT/")]
    public partial class Rastro : object
    {
        
        private string IPField;
        
        private string UsuarioField;
        
        private int CanalField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IP
        {
            get
            {
                return this.IPField;
            }
            set
            {
                this.IPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Canal
        {
            get
            {
                return this.CanalField;
            }
            set
            {
                this.CanalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transferencia", Namespace="http://www.prosoft.cr/CGPCanalesIBAN/TFT/")]
    public partial class Transferencia : object
    {
        
        private Sinpe_TFT.Transaccion DatosDebitoField;
        
        private Sinpe_TFT.Cliente ClienteDestinoField;
        
        private Sinpe_TFT.Cliente ClienteOrigenField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Sinpe_TFT.Transaccion DatosDebito
        {
            get
            {
                return this.DatosDebitoField;
            }
            set
            {
                this.DatosDebitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Sinpe_TFT.Cliente ClienteDestino
        {
            get
            {
                return this.ClienteDestinoField;
            }
            set
            {
                this.ClienteDestinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Sinpe_TFT.Cliente ClienteOrigen
        {
            get
            {
                return this.ClienteOrigenField;
            }
            set
            {
                this.ClienteOrigenField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaccion", Namespace="http://www.prosoft.cr/CGPCanalesIBAN/TFT/")]
    public partial class Transaccion : object
    {
        
        private Sinpe_TFT.E_Monedas MonedaField;
        
        private decimal MontoField;
        
        private string DescripcionField;
        
        private int EntidadOrigenField;
        
        private int CentroCostoField;
        
        private string ServicioField;
        
        private int PuntoIntegracionField;
        
        private int CodigoConceptoField;
        
        private bool FirmaDigitalField;
        
        private string eMAILField;
        
        private string IDCorrelationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Sinpe_TFT.E_Monedas Moneda
        {
            get
            {
                return this.MonedaField;
            }
            set
            {
                this.MonedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Monto
        {
            get
            {
                return this.MontoField;
            }
            set
            {
                this.MontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int EntidadOrigen
        {
            get
            {
                return this.EntidadOrigenField;
            }
            set
            {
                this.EntidadOrigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int CentroCosto
        {
            get
            {
                return this.CentroCostoField;
            }
            set
            {
                this.CentroCostoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Servicio
        {
            get
            {
                return this.ServicioField;
            }
            set
            {
                this.ServicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int PuntoIntegracion
        {
            get
            {
                return this.PuntoIntegracionField;
            }
            set
            {
                this.PuntoIntegracionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int CodigoConcepto
        {
            get
            {
                return this.CodigoConceptoField;
            }
            set
            {
                this.CodigoConceptoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool FirmaDigital
        {
            get
            {
                return this.FirmaDigitalField;
            }
            set
            {
                this.FirmaDigitalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string eMAIL
        {
            get
            {
                return this.eMAILField;
            }
            set
            {
                this.eMAILField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string IDCorrelation
        {
            get
            {
                return this.IDCorrelationField;
            }
            set
            {
                this.IDCorrelationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Cliente", Namespace="http://www.prosoft.cr/CGPCanalesIBAN/TFT/")]
    public partial class Cliente : object
    {
        
        private string IdentificacionField;
        
        private string NombreField;
        
        private string IBANField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Identificacion
        {
            get
            {
                return this.IdentificacionField;
            }
            set
            {
                this.IdentificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IBAN
        {
            get
            {
                return this.IBANField;
            }
            set
            {
                this.IBANField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="E_Monedas", Namespace="http://www.prosoft.cr/CGPCanalesIBAN/TFT/")]
    public enum E_Monedas : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Colones = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dolares = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Euros = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Todas = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EnvioDirectoDebitoCuentaResponseBody", Namespace="http://www.prosoft.cr/CGPCanalesIBAN/TFT/")]
    public partial class EnvioDirectoDebitoCuentaResponseBody : object
    {
        
        private Sinpe_TFT.RespuestaTransaccion[] EnvioDirectoDebitoCuentaResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Sinpe_TFT.RespuestaTransaccion[] EnvioDirectoDebitoCuentaResult
        {
            get
            {
                return this.EnvioDirectoDebitoCuentaResultField;
            }
            set
            {
                this.EnvioDirectoDebitoCuentaResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaTransaccion", Namespace="http://www.prosoft.cr/CGPCanalesIBAN/TFT/")]
    public partial class RespuestaTransaccion : Sinpe_TFT.RespuestaRegistro
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://www.prosoft.cr/CGPCanalesIBAN/TFT/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sinpe_TFT.RespuestaRegistro))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sinpe_TFT.RespuestaTransaccion))]
    public partial class Respuesta : object
    {
        
        private bool EstadoField;
        
        private int MotivoErrorField;
        
        private string MotivoErrorInternoField;
        
        private int ComprobanteTransaccionField;
        
        private string IDCorrelationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MotivoError
        {
            get
            {
                return this.MotivoErrorField;
            }
            set
            {
                this.MotivoErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MotivoErrorInterno
        {
            get
            {
                return this.MotivoErrorInternoField;
            }
            set
            {
                this.MotivoErrorInternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int ComprobanteTransaccion
        {
            get
            {
                return this.ComprobanteTransaccionField;
            }
            set
            {
                this.ComprobanteTransaccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string IDCorrelation
        {
            get
            {
                return this.IDCorrelationField;
            }
            set
            {
                this.IDCorrelationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaRegistro", Namespace="http://www.prosoft.cr/CGPCanalesIBAN/TFT/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sinpe_TFT.RespuestaTransaccion))]
    public partial class RespuestaRegistro : Sinpe_TFT.Respuesta
    {
        
        private int ReferenciaBancoField;
        
        private string ReferenciaSistemaInternoField;
        
        private decimal MontoDebitoField;
        
        private decimal MontoComisionField;
        
        private decimal TipoCambioField;
        
        private decimal MontoTotalField;
        
        private string RequestIdField;
        
        private string CodigoReferenciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ReferenciaBanco
        {
            get
            {
                return this.ReferenciaBancoField;
            }
            set
            {
                this.ReferenciaBancoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReferenciaSistemaInterno
        {
            get
            {
                return this.ReferenciaSistemaInternoField;
            }
            set
            {
                this.ReferenciaSistemaInternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal MontoDebito
        {
            get
            {
                return this.MontoDebitoField;
            }
            set
            {
                this.MontoDebitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal MontoComision
        {
            get
            {
                return this.MontoComisionField;
            }
            set
            {
                this.MontoComisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal TipoCambio
        {
            get
            {
                return this.TipoCambioField;
            }
            set
            {
                this.TipoCambioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal MontoTotal
        {
            get
            {
                return this.MontoTotalField;
            }
            set
            {
                this.MontoTotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string RequestId
        {
            get
            {
                return this.RequestIdField;
            }
            set
            {
                this.RequestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CodigoReferencia
        {
            get
            {
                return this.CodigoReferenciaField;
            }
            set
            {
                this.CodigoReferenciaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtenerInformacionCuentaBody", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    public partial class ObtenerInformacionCuentaBody : object
    {
        
        private Sinpe_TFT.ObtenerInformacionCuentaRequestBody bodyField;
        
        private Sinpe_TFT.IModelosRastroSIF rastroField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinpe_TFT.ObtenerInformacionCuentaRequestBody body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinpe_TFT.IModelosRastroSIF rastro
        {
            get
            {
                return this.rastroField;
            }
            set
            {
                this.rastroField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtenerInformacionCuentaRequestBody", Namespace="http://www.prosoft.cr/CGPCanalesIBAN/TFT/")]
    public partial class ObtenerInformacionCuentaRequestBody : object
    {
        
        private string IBANField;
        
        private string IdentificacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IBAN
        {
            get
            {
                return this.IBANField;
            }
            set
            {
                this.IBANField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Identificacion
        {
            get
            {
                return this.IdentificacionField;
            }
            set
            {
                this.IdentificacionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ObtenerInformacionCuentaResponseBody", Namespace="http://www.prosoft.cr/CGPCanalesIBAN/TFT/")]
    public partial class ObtenerInformacionCuentaResponseBody : object
    {
        
        private Sinpe_TFT.InformacionCuenta ObtenerInformacionCuentaResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Sinpe_TFT.InformacionCuenta ObtenerInformacionCuentaResult
        {
            get
            {
                return this.ObtenerInformacionCuentaResultField;
            }
            set
            {
                this.ObtenerInformacionCuentaResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InformacionCuenta", Namespace="http://www.prosoft.cr/CGPCanalesIBAN/TFT/")]
    public partial class InformacionCuenta : object
    {
        
        private Sinpe_TFT.E_Monedas CodigoMonedaField;
        
        private string NombreField;
        
        private int MotivoRechazoField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Sinpe_TFT.E_Monedas CodigoMoneda
        {
            get
            {
                return this.CodigoMonedaField;
            }
            set
            {
                this.CodigoMonedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int MotivoRechazo
        {
            get
            {
                return this.MotivoRechazoField;
            }
            set
            {
                this.MotivoRechazoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Sinpe_TFT.ISINPE_TFT")]
    public interface ISINPE_TFT
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISINPE_TFT/ServicioDisponible", ReplyAction="http://tempuri.org/ISINPE_TFT/ServicioDisponibleResponse")]
        System.Threading.Tasks.Task<bool> ServicioDisponibleAsync(Sinpe_TFT.IModelosRastroSIF rastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISINPE_TFT/EnvioDirectoDebitoCuenta", ReplyAction="http://tempuri.org/ISINPE_TFT/EnvioDirectoDebitoCuentaResponse")]
        System.Threading.Tasks.Task<Sinpe_TFT.EnvioDirectoDebitoCuentaResponseBody> EnvioDirectoDebitoCuentaAsync(Sinpe_TFT.RegistrarDirectoDebitoCuentaBody body);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISINPE_TFT/ObtenerInformacionCuenta", ReplyAction="http://tempuri.org/ISINPE_TFT/ObtenerInformacionCuentaResponse")]
        System.Threading.Tasks.Task<Sinpe_TFT.ObtenerInformacionCuentaResponseBody> ObtenerInformacionCuentaAsync(Sinpe_TFT.ObtenerInformacionCuentaBody registro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ISINPE_TFTChannel : Sinpe_TFT.ISINPE_TFT, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class SINPE_TFTClient : System.ServiceModel.ClientBase<Sinpe_TFT.ISINPE_TFT>, Sinpe_TFT.ISINPE_TFT
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SINPE_TFTClient() : 
                base(SINPE_TFTClient.GetDefaultBinding(), SINPE_TFTClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISINPE_TFT.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SINPE_TFTClient(EndpointConfiguration endpointConfiguration) : 
                base(SINPE_TFTClient.GetBindingForEndpoint(endpointConfiguration), SINPE_TFTClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SINPE_TFTClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SINPE_TFTClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SINPE_TFTClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SINPE_TFTClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SINPE_TFTClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> ServicioDisponibleAsync(Sinpe_TFT.IModelosRastroSIF rastro)
        {
            return base.Channel.ServicioDisponibleAsync(rastro);
        }
        
        public System.Threading.Tasks.Task<Sinpe_TFT.EnvioDirectoDebitoCuentaResponseBody> EnvioDirectoDebitoCuentaAsync(Sinpe_TFT.RegistrarDirectoDebitoCuentaBody body)
        {
            return base.Channel.EnvioDirectoDebitoCuentaAsync(body);
        }
        
        public System.Threading.Tasks.Task<Sinpe_TFT.ObtenerInformacionCuentaResponseBody> ObtenerInformacionCuentaAsync(Sinpe_TFT.ObtenerInformacionCuentaBody registro)
        {
            return base.Channel.ObtenerInformacionCuentaAsync(registro);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISINPE_TFT))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISINPE_TFT))
            {
                return new System.ServiceModel.EndpointAddress("http://172.16.70.55/Servicios/SINPE_TFT.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SINPE_TFTClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISINPE_TFT);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SINPE_TFTClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISINPE_TFT);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISINPE_TFT,
        }
    }
}
