//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sinpe_CCD
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IModelos.RastroSIF", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    public partial class IModelosRastroSIF : object
    {
        
        private string EquipoField;
        
        private string IPField;
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Equipo
        {
            get
            {
                return this.EquipoField;
            }
            set
            {
                this.EquipoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP
        {
            get
            {
                return this.IPField;
            }
            set
            {
                this.IPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistrarDebitoCuentaBody", Namespace="http://schemas.datacontract.org/2004/07/WCFInterfaces_SINPE.Servicios")]
    public partial class RegistrarDebitoCuentaBody : object
    {
        
        private Sinpe_CCD.RegistrarDebitoCuentaRequestBody bodyField;
        
        private Sinpe_CCD.IModelosRastroSIF rastroField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinpe_CCD.RegistrarDebitoCuentaRequestBody body
        {
            get
            {
                return this.bodyField;
            }
            set
            {
                this.bodyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Sinpe_CCD.IModelosRastroSIF rastro
        {
            get
            {
                return this.rastroField;
            }
            set
            {
                this.rastroField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistrarDebitoCuentaRequestBody", Namespace="http://www.prosoft.cr/CGPCanalesIBAN/CCD/")]
    public partial class RegistrarDebitoCuentaRequestBody : object
    {
        
        private Sinpe_CCD.Rastro RastroField;
        
        private Sinpe_CCD.TransferenciaAS400[] TransaccionesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Sinpe_CCD.Rastro Rastro
        {
            get
            {
                return this.RastroField;
            }
            set
            {
                this.RastroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Sinpe_CCD.TransferenciaAS400[] Transacciones
        {
            get
            {
                return this.TransaccionesField;
            }
            set
            {
                this.TransaccionesField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rastro", Namespace="http://www.prosoft.cr/CGPCanalesIBAN/CCD/")]
    public partial class Rastro : object
    {
        
        private string IPField;
        
        private string UsuarioField;
        
        private int CanalField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string IP
        {
            get
            {
                return this.IPField;
            }
            set
            {
                this.IPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public int Canal
        {
            get
            {
                return this.CanalField;
            }
            set
            {
                this.CanalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransferenciaAS400", Namespace="http://www.prosoft.cr/CGPCanalesIBAN/CCD/")]
    public partial class TransferenciaAS400 : object
    {
        
        private Sinpe_CCD.Transaccion DatosTransaccionField;
        
        private Sinpe_CCD.ClienteAS400 ClienteDestinoField;
        
        private Sinpe_CCD.ClienteAS400 ClienteOrigenField;
        
        private Sinpe_CCD.ServiciosSINPE TipoTransaccionField;
        
        private string IdRequestField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Sinpe_CCD.Transaccion DatosTransaccion
        {
            get
            {
                return this.DatosTransaccionField;
            }
            set
            {
                this.DatosTransaccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public Sinpe_CCD.ClienteAS400 ClienteDestino
        {
            get
            {
                return this.ClienteDestinoField;
            }
            set
            {
                this.ClienteDestinoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public Sinpe_CCD.ClienteAS400 ClienteOrigen
        {
            get
            {
                return this.ClienteOrigenField;
            }
            set
            {
                this.ClienteOrigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public Sinpe_CCD.ServiciosSINPE TipoTransaccion
        {
            get
            {
                return this.TipoTransaccionField;
            }
            set
            {
                this.TipoTransaccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string IdRequest
        {
            get
            {
                return this.IdRequestField;
            }
            set
            {
                this.IdRequestField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Transaccion", Namespace="http://www.prosoft.cr/CGPCanalesIBAN/CCD/")]
    public partial class Transaccion : object
    {
        
        private Sinpe_CCD.E_Monedas MonedaField;
        
        private decimal MontoField;
        
        private string DescripcionField;
        
        private int EntidadOrigenField;
        
        private int CentroCostoField;
        
        private string ServicioField;
        
        private int PuntoIntegracionField;
        
        private int CodigoConceptoField;
        
        private bool FirmaDigitalField;
        
        private string eMAILField;
        
        private string IDCorrelationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public Sinpe_CCD.E_Monedas Moneda
        {
            get
            {
                return this.MonedaField;
            }
            set
            {
                this.MonedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public decimal Monto
        {
            get
            {
                return this.MontoField;
            }
            set
            {
                this.MontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int EntidadOrigen
        {
            get
            {
                return this.EntidadOrigenField;
            }
            set
            {
                this.EntidadOrigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int CentroCosto
        {
            get
            {
                return this.CentroCostoField;
            }
            set
            {
                this.CentroCostoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Servicio
        {
            get
            {
                return this.ServicioField;
            }
            set
            {
                this.ServicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int PuntoIntegracion
        {
            get
            {
                return this.PuntoIntegracionField;
            }
            set
            {
                this.PuntoIntegracionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int CodigoConcepto
        {
            get
            {
                return this.CodigoConceptoField;
            }
            set
            {
                this.CodigoConceptoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public bool FirmaDigital
        {
            get
            {
                return this.FirmaDigitalField;
            }
            set
            {
                this.FirmaDigitalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string eMAIL
        {
            get
            {
                return this.eMAILField;
            }
            set
            {
                this.eMAILField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string IDCorrelation
        {
            get
            {
                return this.IDCorrelationField;
            }
            set
            {
                this.IDCorrelationField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ClienteAS400", Namespace="http://www.prosoft.cr/CGPCanalesIBAN/CCD/")]
    public partial class ClienteAS400 : object
    {
        
        private string IdentificacionField;
        
        private string NombreField;
        
        private string IBANField;
        
        private Sinpe_CCD.E_TipoIdentificacion TipoCedulaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Identificacion
        {
            get
            {
                return this.IdentificacionField;
            }
            set
            {
                this.IdentificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string IBAN
        {
            get
            {
                return this.IBANField;
            }
            set
            {
                this.IBANField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public Sinpe_CCD.E_TipoIdentificacion TipoCedula
        {
            get
            {
                return this.TipoCedulaField;
            }
            set
            {
                this.TipoCedulaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ServiciosSINPE", Namespace="http://www.prosoft.cr/CGPCanalesIBAN/CCD/")]
    public enum ServiciosSINPE : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        TFT = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        DTR = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CCD = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CDD = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="E_Monedas", Namespace="http://www.prosoft.cr/CGPCanalesIBAN/CCD/")]
    public enum E_Monedas : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Colones = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Dolares = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Euros = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Todas = 3,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="E_TipoIdentificacion", Namespace="http://www.prosoft.cr/CGPCanalesIBAN/CCD/")]
    public enum E_TipoIdentificacion : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CNA = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        CJU = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        ERN = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        EDI = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        GOB = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        IAU = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SINPE = 6,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RegistrarDebitoCuentaResponseBody", Namespace="http://www.prosoft.cr/CGPCanalesIBAN/CCD/")]
    public partial class RegistrarDebitoCuentaResponseBody : object
    {
        
        private Sinpe_CCD.RespuestaRegistro[] RegistrarDebitoCuentaResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Sinpe_CCD.RespuestaRegistro[] RegistrarDebitoCuentaResult
        {
            get
            {
                return this.RegistrarDebitoCuentaResultField;
            }
            set
            {
                this.RegistrarDebitoCuentaResultField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RespuestaRegistro", Namespace="http://www.prosoft.cr/CGPCanalesIBAN/CCD/")]
    public partial class RespuestaRegistro : Sinpe_CCD.Respuesta
    {
        
        private int ReferenciaBancoField;
        
        private string ReferenciaSistemaInternoField;
        
        private decimal MontoDebitoField;
        
        private decimal MontoComisionField;
        
        private decimal TipoCambioField;
        
        private decimal MontoTotalField;
        
        private string RequestIdField;
        
        private string CodigoReferenciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int ReferenciaBanco
        {
            get
            {
                return this.ReferenciaBancoField;
            }
            set
            {
                this.ReferenciaBancoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ReferenciaSistemaInterno
        {
            get
            {
                return this.ReferenciaSistemaInternoField;
            }
            set
            {
                this.ReferenciaSistemaInternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public decimal MontoDebito
        {
            get
            {
                return this.MontoDebitoField;
            }
            set
            {
                this.MontoDebitoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public decimal MontoComision
        {
            get
            {
                return this.MontoComisionField;
            }
            set
            {
                this.MontoComisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public decimal TipoCambio
        {
            get
            {
                return this.TipoCambioField;
            }
            set
            {
                this.TipoCambioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=5)]
        public decimal MontoTotal
        {
            get
            {
                return this.MontoTotalField;
            }
            set
            {
                this.MontoTotalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string RequestId
        {
            get
            {
                return this.RequestIdField;
            }
            set
            {
                this.RequestIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string CodigoReferencia
        {
            get
            {
                return this.CodigoReferenciaField;
            }
            set
            {
                this.CodigoReferenciaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Respuesta", Namespace="http://www.prosoft.cr/CGPCanalesIBAN/CCD/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Sinpe_CCD.RespuestaRegistro))]
    public partial class Respuesta : object
    {
        
        private bool EstadoField;
        
        private int MotivoErrorField;
        
        private string MotivoErrorInternoField;
        
        private int ComprobanteTransaccionField;
        
        private string IDCorrelationField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int MotivoError
        {
            get
            {
                return this.MotivoErrorField;
            }
            set
            {
                this.MotivoErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MotivoErrorInterno
        {
            get
            {
                return this.MotivoErrorInternoField;
            }
            set
            {
                this.MotivoErrorInternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int ComprobanteTransaccion
        {
            get
            {
                return this.ComprobanteTransaccionField;
            }
            set
            {
                this.ComprobanteTransaccionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string IDCorrelation
        {
            get
            {
                return this.IDCorrelationField;
            }
            set
            {
                this.IDCorrelationField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Sinpe_CCD.ISINPE_CCD")]
    public interface ISINPE_CCD
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISINPE_CCD/ServicioDisponible", ReplyAction="http://tempuri.org/ISINPE_CCD/ServicioDisponibleResponse")]
        System.Threading.Tasks.Task<bool> ServicioDisponibleAsync(Sinpe_CCD.IModelosRastroSIF rastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISINPE_CCD/RegistrarDebitoCuenta", ReplyAction="http://tempuri.org/ISINPE_CCD/RegistrarDebitoCuentaResponse")]
        System.Threading.Tasks.Task<Sinpe_CCD.RegistrarDebitoCuentaResponseBody> RegistrarDebitoCuentaAsync(Sinpe_CCD.RegistrarDebitoCuentaBody body);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ISINPE_CCDChannel : Sinpe_CCD.ISINPE_CCD, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class SINPE_CCDClient : System.ServiceModel.ClientBase<Sinpe_CCD.ISINPE_CCD>, Sinpe_CCD.ISINPE_CCD
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SINPE_CCDClient() : 
                base(SINPE_CCDClient.GetDefaultBinding(), SINPE_CCDClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_ISINPE_CCD.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SINPE_CCDClient(EndpointConfiguration endpointConfiguration) : 
                base(SINPE_CCDClient.GetBindingForEndpoint(endpointConfiguration), SINPE_CCDClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SINPE_CCDClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SINPE_CCDClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SINPE_CCDClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SINPE_CCDClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SINPE_CCDClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> ServicioDisponibleAsync(Sinpe_CCD.IModelosRastroSIF rastro)
        {
            return base.Channel.ServicioDisponibleAsync(rastro);
        }
        
        public System.Threading.Tasks.Task<Sinpe_CCD.RegistrarDebitoCuentaResponseBody> RegistrarDebitoCuentaAsync(Sinpe_CCD.RegistrarDebitoCuentaBody body)
        {
            return base.Channel.RegistrarDebitoCuentaAsync(body);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISINPE_CCD))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ISINPE_CCD))
            {
                return new System.ServiceModel.EndpointAddress("http://172.16.70.55/Servicios/SINPE_CCD.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SINPE_CCDClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_ISINPE_CCD);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SINPE_CCDClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_ISINPE_CCD);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ISINPE_CCD,
        }
    }
}
