//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CoreInterno
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidacionPerfilTrx_Request", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class ValidacionPerfilTrx_Request : object
    {
        
        private string CuentaIBANField;
        
        private string IBANClienteEntContraparteField;
        
        private string IdClienteField;
        
        private string IdClienteEntContraparteField;
        
        private int ModalidadField;
        
        private string MonedaField;
        
        private decimal MontoField;
        
        private string NombreClienteField;
        
        private string NombreClienteContraparteField;
        
        private string ServicioField;
        
        private int TipoIdClienteField;
        
        private int TipoIdClienteEntContraparteField;
        
        private string TipoMovimientoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaIBAN
        {
            get
            {
                return this.CuentaIBANField;
            }
            set
            {
                this.CuentaIBANField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IBANClienteEntContraparte
        {
            get
            {
                return this.IBANClienteEntContraparteField;
            }
            set
            {
                this.IBANClienteEntContraparteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdCliente
        {
            get
            {
                return this.IdClienteField;
            }
            set
            {
                this.IdClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdClienteEntContraparte
        {
            get
            {
                return this.IdClienteEntContraparteField;
            }
            set
            {
                this.IdClienteEntContraparteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Modalidad
        {
            get
            {
                return this.ModalidadField;
            }
            set
            {
                this.ModalidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Moneda
        {
            get
            {
                return this.MonedaField;
            }
            set
            {
                this.MonedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto
        {
            get
            {
                return this.MontoField;
            }
            set
            {
                this.MontoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCliente
        {
            get
            {
                return this.NombreClienteField;
            }
            set
            {
                this.NombreClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreClienteContraparte
        {
            get
            {
                return this.NombreClienteContraparteField;
            }
            set
            {
                this.NombreClienteContraparteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Servicio
        {
            get
            {
                return this.ServicioField;
            }
            set
            {
                this.ServicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoIdCliente
        {
            get
            {
                return this.TipoIdClienteField;
            }
            set
            {
                this.TipoIdClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoIdClienteEntContraparte
        {
            get
            {
                return this.TipoIdClienteEntContraparteField;
            }
            set
            {
                this.TipoIdClienteEntContraparteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TipoMovimiento
        {
            get
            {
                return this.TipoMovimientoField;
            }
            set
            {
                this.TipoMovimientoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ValidacionPerfilTrx_Response", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class ValidacionPerfilTrx_Response : object
    {
        
        private CoreInterno.CL_AutorizacionPerfilTrx AutorizacionField;
        
        private CoreInterno.CL_Error[] ErroresField;
        
        private bool ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CoreInterno.CL_AutorizacionPerfilTrx Autorizacion
        {
            get
            {
                return this.AutorizacionField;
            }
            set
            {
                this.AutorizacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CoreInterno.CL_Error[] Errores
        {
            get
            {
                return this.ErroresField;
            }
            set
            {
                this.ErroresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CL_AutorizacionPerfilTrx", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class CL_AutorizacionPerfilTrx : object
    {
        
        private string CodMotivoRechazoField;
        
        private CoreInterno.CL_Adicional_Info[] DatosAdicionalesFieldField;
        
        private int EstadoField;
        
        private string MotivoRechazoField;
        
        private string NumRefProcesamientoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodMotivoRechazo
        {
            get
            {
                return this.CodMotivoRechazoField;
            }
            set
            {
                this.CodMotivoRechazoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CoreInterno.CL_Adicional_Info[] DatosAdicionalesField
        {
            get
            {
                return this.DatosAdicionalesFieldField;
            }
            set
            {
                this.DatosAdicionalesFieldField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MotivoRechazo
        {
            get
            {
                return this.MotivoRechazoField;
            }
            set
            {
                this.MotivoRechazoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumRefProcesamiento
        {
            get
            {
                return this.NumRefProcesamientoField;
            }
            set
            {
                this.NumRefProcesamientoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CL_Error", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class CL_Error : object
    {
        
        private string DescripcionField;
        
        private int NumErrorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int NumError
        {
            get
            {
                return this.NumErrorField;
            }
            set
            {
                this.NumErrorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CL_Adicional_Info", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class CL_Adicional_Info : object
    {
        
        private bool MostrarField;
        
        private string NombreField;
        
        private string NombreFisicoField;
        
        private string ValorField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Mostrar
        {
            get
            {
                return this.MostrarField;
            }
            set
            {
                this.MostrarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreFisico
        {
            get
            {
                return this.NombreFisicoField;
            }
            set
            {
                this.NombreFisicoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Valor
        {
            get
            {
                return this.ValorField;
            }
            set
            {
                this.ValorField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuentaIBAN_Request", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class CuentaIBAN_Request : object
    {
        
        private string CuentaIBANField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaIBAN
        {
            get
            {
                return this.CuentaIBANField;
            }
            set
            {
                this.CuentaIBANField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CuentaIBAN_Response", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class CuentaIBAN_Response : object
    {
        
        private CoreInterno.CL_CuentaIBAN CuentaIBANField;
        
        private CoreInterno.CL_Error[] ErroresField;
        
        private bool ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CoreInterno.CL_CuentaIBAN CuentaIBAN
        {
            get
            {
                return this.CuentaIBANField;
            }
            set
            {
                this.CuentaIBANField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CoreInterno.CL_Error[] Errores
        {
            get
            {
                return this.ErroresField;
            }
            set
            {
                this.ErroresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CL_CuentaIBAN", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class CL_CuentaIBAN : object
    {
        
        private string CuentaIBANField;
        
        private string DesProductoField;
        
        private int EstadoField;
        
        private string IdTitularField;
        
        private int MonedaField;
        
        private string NombreTitularField;
        
        private int TipoIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaIBAN
        {
            get
            {
                return this.CuentaIBANField;
            }
            set
            {
                this.CuentaIBANField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DesProducto
        {
            get
            {
                return this.DesProductoField;
            }
            set
            {
                this.DesProductoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdTitular
        {
            get
            {
                return this.IdTitularField;
            }
            set
            {
                this.IdTitularField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Moneda
        {
            get
            {
                return this.MonedaField;
            }
            set
            {
                this.MonedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreTitular
        {
            get
            {
                return this.NombreTitularField;
            }
            set
            {
                this.NombreTitularField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int TipoId
        {
            get
            {
                return this.TipoIdField;
            }
            set
            {
                this.TipoIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SI_Rastro", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class SI_Rastro : object
    {
        
        private int CanalField;
        
        private string IPField;
        
        private string UsuarioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Canal
        {
            get
            {
                return this.CanalField;
            }
            set
            {
                this.CanalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IP
        {
            get
            {
                return this.IPField;
            }
            set
            {
                this.IPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Usuario
        {
            get
            {
                return this.UsuarioField;
            }
            set
            {
                this.UsuarioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CL_DatosTransaccion", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoreInterno.CL_Transaccion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoreInterno.CL_ActualizaTransaccion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoreInterno.TransaccionRechazada))]
    public partial class CL_DatosTransaccion : object
    {
        
        private int CodigoMonedaField;
        
        private int CodigoServicioField;
        
        private string CuentaIBANField;
        
        private string IdRelacionClienteField;
        
        private string IdentificacionField;
        
        private CoreInterno.CL_Adicional_Info[] InformacionAdicionalField;
        
        private decimal MontoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoMoneda
        {
            get
            {
                return this.CodigoMonedaField;
            }
            set
            {
                this.CodigoMonedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoServicio
        {
            get
            {
                return this.CodigoServicioField;
            }
            set
            {
                this.CodigoServicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaIBAN
        {
            get
            {
                return this.CuentaIBANField;
            }
            set
            {
                this.CuentaIBANField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdRelacionCliente
        {
            get
            {
                return this.IdRelacionClienteField;
            }
            set
            {
                this.IdRelacionClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificacion
        {
            get
            {
                return this.IdentificacionField;
            }
            set
            {
                this.IdentificacionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CoreInterno.CL_Adicional_Info[] InformacionAdicional
        {
            get
            {
                return this.InformacionAdicionalField;
            }
            set
            {
                this.InformacionAdicionalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Monto
        {
            get
            {
                return this.MontoField;
            }
            set
            {
                this.MontoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CL_Transaccion", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class CL_Transaccion : CoreInterno.CL_DatosTransaccion
    {
        
        private int CentroCostoField;
        
        private int CodEntidadField;
        
        private string CodigoReferenciaField;
        
        private int ComprobanteCGPField;
        
        private string CuentaIBANContraparteField;
        
        private string DescripcionField;
        
        private System.DateTime FechaCicloField;
        
        private string IdOrigenField;
        
        private string IdentificacionContraparteField;
        
        private int MonedaComisionField;
        
        private decimal MontoComisionField;
        
        private string NombreOrigenField;
        
        private string ServicioField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CentroCosto
        {
            get
            {
                return this.CentroCostoField;
            }
            set
            {
                this.CentroCostoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodEntidad
        {
            get
            {
                return this.CodEntidadField;
            }
            set
            {
                this.CodEntidadField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoReferencia
        {
            get
            {
                return this.CodigoReferenciaField;
            }
            set
            {
                this.CodigoReferenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ComprobanteCGP
        {
            get
            {
                return this.ComprobanteCGPField;
            }
            set
            {
                this.ComprobanteCGPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaIBANContraparte
        {
            get
            {
                return this.CuentaIBANContraparteField;
            }
            set
            {
                this.CuentaIBANContraparteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion
        {
            get
            {
                return this.DescripcionField;
            }
            set
            {
                this.DescripcionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaCiclo
        {
            get
            {
                return this.FechaCicloField;
            }
            set
            {
                this.FechaCicloField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdOrigen
        {
            get
            {
                return this.IdOrigenField;
            }
            set
            {
                this.IdOrigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdentificacionContraparte
        {
            get
            {
                return this.IdentificacionContraparteField;
            }
            set
            {
                this.IdentificacionContraparteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MonedaComision
        {
            get
            {
                return this.MonedaComisionField;
            }
            set
            {
                this.MonedaComisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoComision
        {
            get
            {
                return this.MontoComisionField;
            }
            set
            {
                this.MontoComisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreOrigen
        {
            get
            {
                return this.NombreOrigenField;
            }
            set
            {
                this.NombreOrigenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Servicio
        {
            get
            {
                return this.ServicioField;
            }
            set
            {
                this.ServicioField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CL_ActualizaTransaccion", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class CL_ActualizaTransaccion : CoreInterno.CL_DatosTransaccion
    {
        
        private System.Nullable<int> CodigoRechazoSINPEField;
        
        private string CodigoReferenciaField;
        
        private int ComprobanteCGPField;
        
        private string ComprobanteInternoField;
        
        private string DescripcionRechazoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodigoRechazoSINPE
        {
            get
            {
                return this.CodigoRechazoSINPEField;
            }
            set
            {
                this.CodigoRechazoSINPEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoReferencia
        {
            get
            {
                return this.CodigoReferenciaField;
            }
            set
            {
                this.CodigoReferenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ComprobanteCGP
        {
            get
            {
                return this.ComprobanteCGPField;
            }
            set
            {
                this.ComprobanteCGPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComprobanteInterno
        {
            get
            {
                return this.ComprobanteInternoField;
            }
            set
            {
                this.ComprobanteInternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionRechazo
        {
            get
            {
                return this.DescripcionRechazoField;
            }
            set
            {
                this.DescripcionRechazoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransaccionRechazada", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class TransaccionRechazada : CoreInterno.CL_DatosTransaccion
    {
        
        private System.Nullable<int> CodigoRechazoSINPEField;
        
        private string CodigoReferenciaField;
        
        private int ComprobanteCGPField;
        
        private string ComprobanteInternoField;
        
        private string DescripcionRechazoField;
        
        private int MonedaComisionField;
        
        private decimal MontoComisionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> CodigoRechazoSINPE
        {
            get
            {
                return this.CodigoRechazoSINPEField;
            }
            set
            {
                this.CodigoRechazoSINPEField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoReferencia
        {
            get
            {
                return this.CodigoReferenciaField;
            }
            set
            {
                this.CodigoReferenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ComprobanteCGP
        {
            get
            {
                return this.ComprobanteCGPField;
            }
            set
            {
                this.ComprobanteCGPField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComprobanteInterno
        {
            get
            {
                return this.ComprobanteInternoField;
            }
            set
            {
                this.ComprobanteInternoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionRechazo
        {
            get
            {
                return this.DescripcionRechazoField;
            }
            set
            {
                this.DescripcionRechazoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int MonedaComision
        {
            get
            {
                return this.MonedaComisionField;
            }
            set
            {
                this.MonedaComisionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal MontoComision
        {
            get
            {
                return this.MontoComisionField;
            }
            set
            {
                this.MontoComisionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CL_ResultadoValidacion", Namespace="http://schemas.datacontract.org/2004/07/")]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoreInterno.CL_RespuestaTransaccion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(CoreInterno.CL_RespuestaNotificacion))]
    public partial class CL_ResultadoValidacion : object
    {
        
        private string IdRelacionClienteField;
        
        private CoreInterno.CL_Adicional_Info[] InformacionAdicionalField;
        
        private System.Nullable<int> MotivoErrorField;
        
        private CoreInterno.E_Resultado ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdRelacionCliente
        {
            get
            {
                return this.IdRelacionClienteField;
            }
            set
            {
                this.IdRelacionClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CoreInterno.CL_Adicional_Info[] InformacionAdicional
        {
            get
            {
                return this.InformacionAdicionalField;
            }
            set
            {
                this.InformacionAdicionalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MotivoError
        {
            get
            {
                return this.MotivoErrorField;
            }
            set
            {
                this.MotivoErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CoreInterno.E_Resultado Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CL_RespuestaTransaccion", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class CL_RespuestaTransaccion : CoreInterno.CL_ResultadoValidacion
    {
        
        private string ComprobanteInternoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ComprobanteInterno
        {
            get
            {
                return this.ComprobanteInternoField;
            }
            set
            {
                this.ComprobanteInternoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CL_RespuestaNotificacion", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class CL_RespuestaNotificacion : CoreInterno.CL_ResultadoValidacion
    {
        
        private CoreInterno.E_Preferencia E_PreferenciaField;
        
        private string EmailField;
        
        private string NombreClienteField;
        
        private string TelefonoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CoreInterno.E_Preferencia E_Preferencia
        {
            get
            {
                return this.E_PreferenciaField;
            }
            set
            {
                this.E_PreferenciaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreCliente
        {
            get
            {
                return this.NombreClienteField;
            }
            set
            {
                this.NombreClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Telefono
        {
            get
            {
                return this.TelefonoField;
            }
            set
            {
                this.TelefonoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="E_Resultado", Namespace="http://schemas.datacontract.org/2004/07/")]
    public enum E_Resultado : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exitoso = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Rechazo = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="E_Preferencia", Namespace="http://schemas.datacontract.org/2004/07/")]
    public enum E_Preferencia : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Correo = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        SMS = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ambos = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ninguno = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CL_ValidaCuenta", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class CL_ValidaCuenta : object
    {
        
        private System.Nullable<int> MotivoErrorField;
        
        private CoreInterno.E_Resultado ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MotivoError
        {
            get
            {
                return this.MotivoErrorField;
            }
            set
            {
                this.MotivoErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CoreInterno.E_Resultado Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CL_ObtieneInfoCuenta", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class CL_ObtieneInfoCuenta : object
    {
        
        private CoreInterno.E_Estado EstadoField;
        
        private int MonedaField;
        
        private System.Nullable<int> MotivoErrorField;
        
        private string NombreTitularField;
        
        private CoreInterno.E_Resultado ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CoreInterno.E_Estado Estado
        {
            get
            {
                return this.EstadoField;
            }
            set
            {
                this.EstadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Moneda
        {
            get
            {
                return this.MonedaField;
            }
            set
            {
                this.MonedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> MotivoError
        {
            get
            {
                return this.MotivoErrorField;
            }
            set
            {
                this.MotivoErrorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NombreTitular
        {
            get
            {
                return this.NombreTitularField;
            }
            set
            {
                this.NombreTitularField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CoreInterno.E_Resultado Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="E_Estado", Namespace="http://schemas.datacontract.org/2004/07/")]
    public enum E_Estado : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Activa = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Cerrada = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Bloqueada = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoActiva = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CL_ResultadoActualizacion", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class CL_ResultadoActualizacion : object
    {
        
        private string IdRelacionClienteField;
        
        private CoreInterno.E_ResultadoActualizacion ResultadoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string IdRelacionCliente
        {
            get
            {
                return this.IdRelacionClienteField;
            }
            set
            {
                this.IdRelacionClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CoreInterno.E_ResultadoActualizacion Resultado
        {
            get
            {
                return this.ResultadoField;
            }
            set
            {
                this.ResultadoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="E_ResultadoActualizacion", Namespace="http://schemas.datacontract.org/2004/07/")]
    public enum E_ResultadoActualizacion : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Exitoso = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoExiste = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NoPermitido = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CL_InformacionCliente", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class CL_InformacionCliente : object
    {
        
        private bool ExisteField;
        
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Existe
        {
            get
            {
                return this.ExisteField;
            }
            set
            {
                this.ExisteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre
        {
            get
            {
                return this.NombreField;
            }
            set
            {
                this.NombreField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CL_ProductoCliente", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class CL_ProductoCliente : object
    {
        
        private int CodigoMonedaField;
        
        private string CuentaClienteField;
        
        private decimal CuotaField;
        
        private string DescripcionServicioField;
        
        private CoreInterno.E_MovimientosPermitidosProducto MovimientosPermitidosField;
        
        private decimal SaldoField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CodigoMoneda
        {
            get
            {
                return this.CodigoMonedaField;
            }
            set
            {
                this.CodigoMonedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaCliente
        {
            get
            {
                return this.CuentaClienteField;
            }
            set
            {
                this.CuentaClienteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Cuota
        {
            get
            {
                return this.CuotaField;
            }
            set
            {
                this.CuotaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DescripcionServicio
        {
            get
            {
                return this.DescripcionServicioField;
            }
            set
            {
                this.DescripcionServicioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public CoreInterno.E_MovimientosPermitidosProducto MovimientosPermitidos
        {
            get
            {
                return this.MovimientosPermitidosField;
            }
            set
            {
                this.MovimientosPermitidosField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Saldo
        {
            get
            {
                return this.SaldoField;
            }
            set
            {
                this.SaldoField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="E_MovimientosPermitidosProducto", Namespace="http://schemas.datacontract.org/2004/07/")]
    public enum E_MovimientosPermitidosProducto : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Acreditar = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Debitar = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ambos = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Ninguno = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CL_ResultadoTipoCambio", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class CL_ResultadoTipoCambio : object
    {
        
        private decimal TipoCambioAplicadoField;
        
        private decimal montoTotalField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal TipoCambioAplicado
        {
            get
            {
                return this.TipoCambioAplicadoField;
            }
            set
            {
                this.TipoCambioAplicadoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal montoTotal
        {
            get
            {
                return this.montoTotalField;
            }
            set
            {
                this.montoTotalField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CL_Notificacion", Namespace="http://schemas.datacontract.org/2004/07/")]
    public partial class CL_Notificacion : object
    {
        
        private string CuentaIBANField;
        
        private string IdentificacionField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuentaIBAN
        {
            get
            {
                return this.CuentaIBANField;
            }
            set
            {
                this.CuentaIBANField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Identificacion
        {
            get
            {
                return this.IdentificacionField;
            }
            set
            {
                this.IdentificacionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://prosoft.CGPbackOffice/", ConfigurationName="CoreInterno.ICoreInterno")]
    public interface ICoreInterno
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prosoft.CGPbackOffice/ICoreInterno/ServicioDisponible", ReplyAction="http://prosoft.CGPbackOffice/ICoreInterno/ServicioDisponibleResponse")]
        System.Threading.Tasks.Task<bool> ServicioDisponibleAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prosoft.CGPbackOffice/ICoreInterno/ValidarPerfilTransaccional", ReplyAction="http://prosoft.CGPbackOffice/ICoreInterno/ValidarPerfilTransaccionalResponse")]
        System.Threading.Tasks.Task<CoreInterno.ValidacionPerfilTrx_Response> ValidarPerfilTransaccionalAsync(CoreInterno.ValidacionPerfilTrx_Request transaccion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prosoft.CGPbackOffice/ICoreInterno/ObtenerCuentaIBAN", ReplyAction="http://prosoft.CGPbackOffice/ICoreInterno/ObtenerCuentaIBANResponse")]
        System.Threading.Tasks.Task<CoreInterno.CuentaIBAN_Response> ObtenerCuentaIBANAsync(CoreInterno.CuentaIBAN_Request DatosCuenta);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prosoft.CGPbackOffice/ICoreInterno/ValidaDebitos", ReplyAction="http://prosoft.CGPbackOffice/ICoreInterno/ValidaDebitosResponse")]
        System.Threading.Tasks.Task<CoreInterno.CL_ResultadoValidacion[]> ValidaDebitosAsync(CoreInterno.SI_Rastro rastro, CoreInterno.CL_DatosTransaccion[] transacciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prosoft.CGPbackOffice/ICoreInterno/ValidaCreditos", ReplyAction="http://prosoft.CGPbackOffice/ICoreInterno/ValidaCreditosResponse")]
        System.Threading.Tasks.Task<CoreInterno.CL_ResultadoValidacion[]> ValidaCreditosAsync(CoreInterno.SI_Rastro rastro, CoreInterno.CL_DatosTransaccion[] transacciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prosoft.CGPbackOffice/ICoreInterno/ValidaCuenta", ReplyAction="http://prosoft.CGPbackOffice/ICoreInterno/ValidaCuentaResponse")]
        System.Threading.Tasks.Task<CoreInterno.CL_ValidaCuenta> ValidaCuentaAsync(string Identificacion, string CuentaIBAN, int CodigoMoneda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prosoft.CGPbackOffice/ICoreInterno/ObtieneInfoCuenta", ReplyAction="http://prosoft.CGPbackOffice/ICoreInterno/ObtieneInfoCuentaResponse")]
        System.Threading.Tasks.Task<CoreInterno.CL_ObtieneInfoCuenta> ObtieneInfoCuentaAsync(string Identificacion, string CuentaIBAN);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://prosoft.CGPbackOffice/ICoreInterno/ObtieneEstadoTransaccion", ReplyAction="http://prosoft.CGPbackOffice/ICoreInterno/ObtieneEstadoTransaccionResponse")]
        System.Threading.Tasks.Task<CoreInterno.ObtieneEstadoTransaccionResponse> ObtieneEstadoTransaccionAsync(CoreInterno.ObtieneEstadoTransaccionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prosoft.CGPbackOffice/ICoreInterno/AplicaDebitosCongelados", ReplyAction="http://prosoft.CGPbackOffice/ICoreInterno/AplicaDebitosCongeladosResponse")]
        System.Threading.Tasks.Task<CoreInterno.CL_RespuestaTransaccion[]> AplicaDebitosCongeladosAsync(CoreInterno.SI_Rastro rastro, CoreInterno.CL_Transaccion[] transacciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prosoft.CGPbackOffice/ICoreInterno/AplicaCreditosCongelados", ReplyAction="http://prosoft.CGPbackOffice/ICoreInterno/AplicaCreditosCongeladosResponse")]
        System.Threading.Tasks.Task<CoreInterno.CL_RespuestaTransaccion[]> AplicaCreditosCongeladosAsync(CoreInterno.SI_Rastro rastro, CoreInterno.CL_Transaccion[] transacciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prosoft.CGPbackOffice/ICoreInterno/ConfirmaCreditosCongelados", ReplyAction="http://prosoft.CGPbackOffice/ICoreInterno/ConfirmaCreditosCongeladosResponse")]
        System.Threading.Tasks.Task<CoreInterno.CL_ResultadoActualizacion[]> ConfirmaCreditosCongeladosAsync(CoreInterno.SI_Rastro rastro, CoreInterno.CL_ActualizaTransaccion[] transacciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prosoft.CGPbackOffice/ICoreInterno/ConfirmaDebitosCongelados", ReplyAction="http://prosoft.CGPbackOffice/ICoreInterno/ConfirmaDebitosCongeladosResponse")]
        System.Threading.Tasks.Task<CoreInterno.CL_ResultadoActualizacion[]> ConfirmaDebitosCongeladosAsync(CoreInterno.SI_Rastro rastro, CoreInterno.CL_ActualizaTransaccion[] transacciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prosoft.CGPbackOffice/ICoreInterno/AplicaTransferenciasFirmes", ReplyAction="http://prosoft.CGPbackOffice/ICoreInterno/AplicaTransferenciasFirmesResponse")]
        System.Threading.Tasks.Task<CoreInterno.CL_RespuestaTransaccion[]> AplicaTransferenciasFirmesAsync(CoreInterno.SI_Rastro rastro, CoreInterno.CL_Transaccion[] transacciones);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://prosoft.CGPbackOffice/ICoreInterno/SaldoDisponible", ReplyAction="http://prosoft.CGPbackOffice/ICoreInterno/SaldoDisponibleResponse")]
        System.Threading.Tasks.Task<CoreInterno.SaldoDisponibleResponse> SaldoDisponibleAsync(CoreInterno.SaldoDisponibleRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://prosoft.CGPbackOffice/ICoreInterno/ComisionRespectiva", ReplyAction="http://prosoft.CGPbackOffice/ICoreInterno/ComisionRespectivaResponse")]
        System.Threading.Tasks.Task<CoreInterno.ComisionRespectivaResponse> ComisionRespectivaAsync(CoreInterno.ComisionRespectivaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prosoft.CGPbackOffice/ICoreInterno/ReversaCreditos", ReplyAction="http://prosoft.CGPbackOffice/ICoreInterno/ReversaCreditosResponse")]
        System.Threading.Tasks.Task<CoreInterno.CL_ResultadoActualizacion[]> ReversaCreditosAsync(CoreInterno.SI_Rastro rastro, CoreInterno.TransaccionRechazada[] transacciones);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prosoft.CGPbackOffice/ICoreInterno/ReversaDebitos", ReplyAction="http://prosoft.CGPbackOffice/ICoreInterno/ReversaDebitosResponse")]
        System.Threading.Tasks.Task<CoreInterno.CL_ResultadoActualizacion[]> ReversaDebitosAsync(CoreInterno.SI_Rastro rastro, CoreInterno.TransaccionRechazada[] transacciones);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://prosoft.CGPbackOffice/ICoreInterno/ObtenerInformacionCliente", ReplyAction="http://prosoft.CGPbackOffice/ICoreInterno/ObtenerInformacionClienteResponse")]
        System.Threading.Tasks.Task<CoreInterno.ObtenerInformacionClienteResponse> ObtenerInformacionClienteAsync(CoreInterno.ObtenerInformacionClienteRequest request);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://prosoft.CGPbackOffice/ICoreInterno/ObtenerProductosPorCliente", ReplyAction="http://prosoft.CGPbackOffice/ICoreInterno/ObtenerProductosPorClienteResponse")]
        System.Threading.Tasks.Task<CoreInterno.ObtenerProductosPorClienteResponse> ObtenerProductosPorClienteAsync(CoreInterno.ObtenerProductosPorClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prosoft.CGPbackOffice/ICoreInterno/ObtenerTipoCambio", ReplyAction="http://prosoft.CGPbackOffice/ICoreInterno/ObtenerTipoCambioResponse")]
        System.Threading.Tasks.Task<CoreInterno.CL_ResultadoTipoCambio> ObtenerTipoCambioAsync(CoreInterno.SI_Rastro Rastro, int CodigoServicio, string CuentaOrigen, string CuentaDestino, decimal Monto, int Moneda);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prosoft.CGPbackOffice/ICoreInterno/ActualizarFechaCiclo", ReplyAction="http://prosoft.CGPbackOffice/ICoreInterno/ActualizarFechaCicloResponse")]
        System.Threading.Tasks.Task<bool> ActualizarFechaCicloAsync(int ComprobanteCGP, string DocumentoSistemaInterno, int ServicioSINPE, System.DateTime FechaCiclo, string CodigoReferenciaAnterior, string CodigoReferenciaNuevo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prosoft.CGPbackOffice/ICoreInterno/LiquidarCiclo", ReplyAction="http://prosoft.CGPbackOffice/ICoreInterno/LiquidarCicloResponse")]
        System.Threading.Tasks.Task<bool> LiquidarCicloAsync(int[] EntidadesAplazadas, int ServicioSINPE, string Modalidad, System.DateTime FechaCiclo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://prosoft.CGPbackOffice/ICoreInterno/PreferenciasNotificacion", ReplyAction="http://prosoft.CGPbackOffice/ICoreInterno/PreferenciasNotificacionResponse")]
        System.Threading.Tasks.Task<CoreInterno.CL_RespuestaNotificacion[]> PreferenciasNotificacionAsync(CoreInterno.SI_Rastro rastro, CoreInterno.CL_Notificacion[] notificacion);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtieneEstadoTransaccion", WrapperNamespace="http://prosoft.CGPbackOffice/", IsWrapped=true)]
    public partial class ObtieneEstadoTransaccionRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=0)]
        public string CodigoReferenciaSINPE;
        
        public ObtieneEstadoTransaccionRequest()
        {
        }
        
        public ObtieneEstadoTransaccionRequest(string CodigoReferenciaSINPE)
        {
            this.CodigoReferenciaSINPE = CodigoReferenciaSINPE;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtieneEstadoTransaccionResponse", WrapperNamespace="http://prosoft.CGPbackOffice/", IsWrapped=true)]
    public partial class ObtieneEstadoTransaccionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=0)]
        public bool ObtieneEstadoTransaccionResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=1)]
        public string ComprobanteInterno;
        
        public ObtieneEstadoTransaccionResponse()
        {
        }
        
        public ObtieneEstadoTransaccionResponse(bool ObtieneEstadoTransaccionResult, string ComprobanteInterno)
        {
            this.ObtieneEstadoTransaccionResult = ObtieneEstadoTransaccionResult;
            this.ComprobanteInterno = ComprobanteInterno;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaldoDisponible", WrapperNamespace="http://prosoft.CGPbackOffice/", IsWrapped=true)]
    public partial class SaldoDisponibleRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=0)]
        public CoreInterno.SI_Rastro rastro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=1)]
        public string cuentaIBAN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=2)]
        public string identificacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=3)]
        public int codigoMoneda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=4)]
        public decimal monto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=5)]
        public int codigoServicio;
        
        public SaldoDisponibleRequest()
        {
        }
        
        public SaldoDisponibleRequest(CoreInterno.SI_Rastro rastro, string cuentaIBAN, string identificacion, int codigoMoneda, decimal monto, int codigoServicio)
        {
            this.rastro = rastro;
            this.cuentaIBAN = cuentaIBAN;
            this.identificacion = identificacion;
            this.codigoMoneda = codigoMoneda;
            this.monto = monto;
            this.codigoServicio = codigoServicio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="SaldoDisponibleResponse", WrapperNamespace="http://prosoft.CGPbackOffice/", IsWrapped=true)]
    public partial class SaldoDisponibleResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=0)]
        public CoreInterno.E_Resultado SaldoDisponibleResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=1)]
        public bool disponible;
        
        public SaldoDisponibleResponse()
        {
        }
        
        public SaldoDisponibleResponse(CoreInterno.E_Resultado SaldoDisponibleResult, bool disponible)
        {
            this.SaldoDisponibleResult = SaldoDisponibleResult;
            this.disponible = disponible;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ComisionRespectiva", WrapperNamespace="http://prosoft.CGPbackOffice/", IsWrapped=true)]
    public partial class ComisionRespectivaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=0)]
        public CoreInterno.SI_Rastro rastro;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=1)]
        public string cuentaIBAN;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=2)]
        public string identificacion;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=3)]
        public int codigoMoneda;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=4)]
        public decimal monto;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=5)]
        public int codigoServicio;
        
        public ComisionRespectivaRequest()
        {
        }
        
        public ComisionRespectivaRequest(CoreInterno.SI_Rastro rastro, string cuentaIBAN, string identificacion, int codigoMoneda, decimal monto, int codigoServicio)
        {
            this.rastro = rastro;
            this.cuentaIBAN = cuentaIBAN;
            this.identificacion = identificacion;
            this.codigoMoneda = codigoMoneda;
            this.monto = monto;
            this.codigoServicio = codigoServicio;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ComisionRespectivaResponse", WrapperNamespace="http://prosoft.CGPbackOffice/", IsWrapped=true)]
    public partial class ComisionRespectivaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=0)]
        public CoreInterno.E_Resultado ComisionRespectivaResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=1)]
        public decimal comision;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=2)]
        public int codigoMonedaComision;
        
        public ComisionRespectivaResponse()
        {
        }
        
        public ComisionRespectivaResponse(CoreInterno.E_Resultado ComisionRespectivaResult, decimal comision, int codigoMonedaComision)
        {
            this.ComisionRespectivaResult = ComisionRespectivaResult;
            this.comision = comision;
            this.codigoMonedaComision = codigoMonedaComision;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerInformacionCliente", WrapperNamespace="http://prosoft.CGPbackOffice/", IsWrapped=true)]
    public partial class ObtenerInformacionClienteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=0)]
        public string identificacion;
        
        public ObtenerInformacionClienteRequest()
        {
        }
        
        public ObtenerInformacionClienteRequest(string identificacion)
        {
            this.identificacion = identificacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerInformacionClienteResponse", WrapperNamespace="http://prosoft.CGPbackOffice/", IsWrapped=true)]
    public partial class ObtenerInformacionClienteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=0)]
        public CoreInterno.E_Resultado ObtenerInformacionClienteResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=1)]
        public CoreInterno.CL_InformacionCliente informacionCliente;
        
        public ObtenerInformacionClienteResponse()
        {
        }
        
        public ObtenerInformacionClienteResponse(CoreInterno.E_Resultado ObtenerInformacionClienteResult, CoreInterno.CL_InformacionCliente informacionCliente)
        {
            this.ObtenerInformacionClienteResult = ObtenerInformacionClienteResult;
            this.informacionCliente = informacionCliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerProductosPorCliente", WrapperNamespace="http://prosoft.CGPbackOffice/", IsWrapped=true)]
    public partial class ObtenerProductosPorClienteRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=0)]
        public string identificacion;
        
        public ObtenerProductosPorClienteRequest()
        {
        }
        
        public ObtenerProductosPorClienteRequest(string identificacion)
        {
            this.identificacion = identificacion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ObtenerProductosPorClienteResponse", WrapperNamespace="http://prosoft.CGPbackOffice/", IsWrapped=true)]
    public partial class ObtenerProductosPorClienteResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=0)]
        public CoreInterno.E_Resultado ObtenerProductosPorClienteResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://prosoft.CGPbackOffice/", Order=1)]
        public CoreInterno.CL_ProductoCliente[] productos;
        
        public ObtenerProductosPorClienteResponse()
        {
        }
        
        public ObtenerProductosPorClienteResponse(CoreInterno.E_Resultado ObtenerProductosPorClienteResult, CoreInterno.CL_ProductoCliente[] productos)
        {
            this.ObtenerProductosPorClienteResult = ObtenerProductosPorClienteResult;
            this.productos = productos;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ICoreInternoChannel : CoreInterno.ICoreInterno, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class CoreInternoClient : System.ServiceModel.ClientBase<CoreInterno.ICoreInterno>, CoreInterno.ICoreInterno
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CoreInternoClient(EndpointConfiguration endpointConfiguration) : 
                base(CoreInternoClient.GetBindingForEndpoint(endpointConfiguration), CoreInternoClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CoreInternoClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CoreInternoClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CoreInternoClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CoreInternoClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CoreInternoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<bool> ServicioDisponibleAsync()
        {
            return base.Channel.ServicioDisponibleAsync();
        }
        
        public System.Threading.Tasks.Task<CoreInterno.ValidacionPerfilTrx_Response> ValidarPerfilTransaccionalAsync(CoreInterno.ValidacionPerfilTrx_Request transaccion)
        {
            return base.Channel.ValidarPerfilTransaccionalAsync(transaccion);
        }
        
        public System.Threading.Tasks.Task<CoreInterno.CuentaIBAN_Response> ObtenerCuentaIBANAsync(CoreInterno.CuentaIBAN_Request DatosCuenta)
        {
            return base.Channel.ObtenerCuentaIBANAsync(DatosCuenta);
        }
        
        public System.Threading.Tasks.Task<CoreInterno.CL_ResultadoValidacion[]> ValidaDebitosAsync(CoreInterno.SI_Rastro rastro, CoreInterno.CL_DatosTransaccion[] transacciones)
        {
            return base.Channel.ValidaDebitosAsync(rastro, transacciones);
        }
        
        public System.Threading.Tasks.Task<CoreInterno.CL_ResultadoValidacion[]> ValidaCreditosAsync(CoreInterno.SI_Rastro rastro, CoreInterno.CL_DatosTransaccion[] transacciones)
        {
            return base.Channel.ValidaCreditosAsync(rastro, transacciones);
        }
        
        public System.Threading.Tasks.Task<CoreInterno.CL_ValidaCuenta> ValidaCuentaAsync(string Identificacion, string CuentaIBAN, int CodigoMoneda)
        {
            return base.Channel.ValidaCuentaAsync(Identificacion, CuentaIBAN, CodigoMoneda);
        }
        
        public System.Threading.Tasks.Task<CoreInterno.CL_ObtieneInfoCuenta> ObtieneInfoCuentaAsync(string Identificacion, string CuentaIBAN)
        {
            return base.Channel.ObtieneInfoCuentaAsync(Identificacion, CuentaIBAN);
        }
        
        public System.Threading.Tasks.Task<CoreInterno.ObtieneEstadoTransaccionResponse> ObtieneEstadoTransaccionAsync(CoreInterno.ObtieneEstadoTransaccionRequest request)
        {
            return base.Channel.ObtieneEstadoTransaccionAsync(request);
        }
        
        public System.Threading.Tasks.Task<CoreInterno.CL_RespuestaTransaccion[]> AplicaDebitosCongeladosAsync(CoreInterno.SI_Rastro rastro, CoreInterno.CL_Transaccion[] transacciones)
        {
            return base.Channel.AplicaDebitosCongeladosAsync(rastro, transacciones);
        }
        
        public System.Threading.Tasks.Task<CoreInterno.CL_RespuestaTransaccion[]> AplicaCreditosCongeladosAsync(CoreInterno.SI_Rastro rastro, CoreInterno.CL_Transaccion[] transacciones)
        {
            return base.Channel.AplicaCreditosCongeladosAsync(rastro, transacciones);
        }
        
        public System.Threading.Tasks.Task<CoreInterno.CL_ResultadoActualizacion[]> ConfirmaCreditosCongeladosAsync(CoreInterno.SI_Rastro rastro, CoreInterno.CL_ActualizaTransaccion[] transacciones)
        {
            return base.Channel.ConfirmaCreditosCongeladosAsync(rastro, transacciones);
        }
        
        public System.Threading.Tasks.Task<CoreInterno.CL_ResultadoActualizacion[]> ConfirmaDebitosCongeladosAsync(CoreInterno.SI_Rastro rastro, CoreInterno.CL_ActualizaTransaccion[] transacciones)
        {
            return base.Channel.ConfirmaDebitosCongeladosAsync(rastro, transacciones);
        }
        
        public System.Threading.Tasks.Task<CoreInterno.CL_RespuestaTransaccion[]> AplicaTransferenciasFirmesAsync(CoreInterno.SI_Rastro rastro, CoreInterno.CL_Transaccion[] transacciones)
        {
            return base.Channel.AplicaTransferenciasFirmesAsync(rastro, transacciones);
        }
        
        public System.Threading.Tasks.Task<CoreInterno.SaldoDisponibleResponse> SaldoDisponibleAsync(CoreInterno.SaldoDisponibleRequest request)
        {
            return base.Channel.SaldoDisponibleAsync(request);
        }
        
        public System.Threading.Tasks.Task<CoreInterno.ComisionRespectivaResponse> ComisionRespectivaAsync(CoreInterno.ComisionRespectivaRequest request)
        {
            return base.Channel.ComisionRespectivaAsync(request);
        }
        
        public System.Threading.Tasks.Task<CoreInterno.CL_ResultadoActualizacion[]> ReversaCreditosAsync(CoreInterno.SI_Rastro rastro, CoreInterno.TransaccionRechazada[] transacciones)
        {
            return base.Channel.ReversaCreditosAsync(rastro, transacciones);
        }
        
        public System.Threading.Tasks.Task<CoreInterno.CL_ResultadoActualizacion[]> ReversaDebitosAsync(CoreInterno.SI_Rastro rastro, CoreInterno.TransaccionRechazada[] transacciones)
        {
            return base.Channel.ReversaDebitosAsync(rastro, transacciones);
        }
        
        public System.Threading.Tasks.Task<CoreInterno.ObtenerInformacionClienteResponse> ObtenerInformacionClienteAsync(CoreInterno.ObtenerInformacionClienteRequest request)
        {
            return base.Channel.ObtenerInformacionClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CoreInterno.ObtenerProductosPorClienteResponse> ObtenerProductosPorClienteAsync(CoreInterno.ObtenerProductosPorClienteRequest request)
        {
            return base.Channel.ObtenerProductosPorClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<CoreInterno.CL_ResultadoTipoCambio> ObtenerTipoCambioAsync(CoreInterno.SI_Rastro Rastro, int CodigoServicio, string CuentaOrigen, string CuentaDestino, decimal Monto, int Moneda)
        {
            return base.Channel.ObtenerTipoCambioAsync(Rastro, CodigoServicio, CuentaOrigen, CuentaDestino, Monto, Moneda);
        }
        
        public System.Threading.Tasks.Task<bool> ActualizarFechaCicloAsync(int ComprobanteCGP, string DocumentoSistemaInterno, int ServicioSINPE, System.DateTime FechaCiclo, string CodigoReferenciaAnterior, string CodigoReferenciaNuevo)
        {
            return base.Channel.ActualizarFechaCicloAsync(ComprobanteCGP, DocumentoSistemaInterno, ServicioSINPE, FechaCiclo, CodigoReferenciaAnterior, CodigoReferenciaNuevo);
        }
        
        public System.Threading.Tasks.Task<bool> LiquidarCicloAsync(int[] EntidadesAplazadas, int ServicioSINPE, string Modalidad, System.DateTime FechaCiclo)
        {
            return base.Channel.LiquidarCicloAsync(EntidadesAplazadas, ServicioSINPE, Modalidad, FechaCiclo);
        }
        
        public System.Threading.Tasks.Task<CoreInterno.CL_RespuestaNotificacion[]> PreferenciasNotificacionAsync(CoreInterno.SI_Rastro rastro, CoreInterno.CL_Notificacion[] notificacion)
        {
            return base.Channel.PreferenciasNotificacionAsync(rastro, notificacion);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICoreInterno))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_ICoreInterno))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_ICoreInterno))
            {
                System.ServiceModel.NetTcpBinding result = new System.ServiceModel.NetTcpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_ICoreInterno))
            {
                return new System.ServiceModel.EndpointAddress("http://webserver2/CORE_Bridge/CoreInternoServicio.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpsBinding_ICoreInterno))
            {
                return new System.ServiceModel.EndpointAddress("https://www.progrxweb.com/CORE_Bridge/CoreInternoServicio.svc");
            }
            if ((endpointConfiguration == EndpointConfiguration.NetTcpBinding_ICoreInterno))
            {
                return new System.ServiceModel.EndpointAddress("net.tcp://webserver2/CORE_Bridge/CoreInternoServicio.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_ICoreInterno,
            
            BasicHttpsBinding_ICoreInterno,
            
            NetTcpBinding_ICoreInterno,
        }
    }
}
